/** Delta Paper Trading boot. */
(async function(){
'use strict';
DELTA_LOGGER.log('[Boot] Starting Delta Paper Trading...');
const loadScript=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error(src+' failed to load'));document.head.appendChild(s);});
await loadScript('./js/FinancialEngine.js');await loadScript('./js/TradingEngine.js');await loadScript('./js/services/CandleStore.js');await loadScript('./js/services/ChartDataService.js');await loadScript('./js/ChartReplay.js');await loadScript('./js/ChartIntegrationPatch.js');await loadScript('./js/MarketDataStatusPatch.js');
const config=DELTA_CONFIG,eventBusInstance=eventBus,apiService=new DeltaApiService(config),wsService=new WebSocketService(config);await storage.init().catch(e=>DELTA_LOGGER.warn('[Boot] IndexedDB init failed, using localStorage fallback'));const candleStore=new CandleStore();await candleStore.init().catch(e=>DELTA_LOGGER.warn('[Boot] Candle store unavailable:',e.message));
const stateManager=new AppState(config,storage);await stateManager.load();const marketService=new MarketDataService(config,apiService,wsService),validator=new InputValidator(config);const chartDataService=new ChartDataService(config,candleStore);
const fundingSimulator=new FundingSimulator(config,stateManager,marketService,eventBusInstance),riskMetrics=new RiskMetrics(config,stateManager),keyboardShortcuts=new KeyboardShortcuts(config,eventBusInstance),app=new DeltaPaperApp(config,stateManager,validator,marketService);
window.app=app;window.fundingSimulator=fundingSimulator;window.riskMetrics=riskMetrics;window.keyboardShortcuts=keyboardShortcuts;window.eventBus=eventBusInstance;window.financialEngine=new FinancialEngine(config,stateManager,marketService);window.tradingEngine=new TradingEngine(config,stateManager,marketService,window.financialEngine);window.candleStore=candleStore;window.chartDataService=chartDataService;app.financial=window.financialEngine;app.trading=window.tradingEngine;
app.init();fundingSimulator.init();keyboardShortcuts.init();marketService.init().then(()=>DELTA_LOGGER.log('[Boot] Market data initialized')).catch(e=>DELTA_LOGGER.error('[Boot] market init failed',e));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>DELTA_LOGGER.error('[Boot] Service Worker failed',e));DELTA_LOGGER.log('[Boot] Application ready');})();
