/* Account integration + risk analytics. FinancialEngine owns all accounting mutations. */
(function(global){
'use strict';
const round=global.FINANCIAL_ROUND||(n=>Number(Number(n).toFixed(8)));
if(global.AppState){
 const oldDefault=AppState.prototype.createDefault;
 AppState.prototype.createDefault=function(){const s=oldDefault.call(this);s.grossProfit=0;s.grossLoss=0;s.tradeCount=0;s.tradeArchive=[];s.peakEquity=0;s.fundingNet=0;return s;};
 const oldMigrate=AppState.prototype.migrateState;
 AppState.prototype.migrateState=function(){oldMigrate.call(this);const s=this.state;s.tradeArchive=Array.isArray(s.tradeArchive)?s.tradeArchive:[];s.grossProfit=Number.isFinite(s.grossProfit)?s.grossProfit:0;s.grossLoss=Number.isFinite(s.grossLoss)?s.grossLoss:0;s.tradeCount=Number.isFinite(s.tradeCount)?s.tradeCount:(s.wins||0)+(s.losses||0);s.peakEquity=Number.isFinite(s.peakEquity)?s.peakEquity:0;s.fundingNet=Number.isFinite(s.fundingNet)?s.fundingNet:0;};
}
if(!global.DeltaPaperApp)return;
const P=DeltaPaperApp.prototype;
P.applyFill=function(sym,side,price,qty,lev,fee,lots){try{this.financial=this.financial||global.financialEngine;this.financial.fill(sym,side,price,qty,lev,fee,lots,'MARKET');this.flushSave(true);this.markDirty();return true;}catch(e){this.toast('Order rejected',e.message,'err');return false;}};
P.liqPrice=function(pos){return this.financial.liquidationPrice(pos);};
P.totals=function(){const a=this.financial.accountSnapshot(this.state.rate||this.config.BASE_RATE);return {equity:a.unrealizedPnlUsd,lockedMargin:a.lockedMarginUsd,totalEquityUsd:a.equityUsd,accountEquityUsd:a.equityUsd,availableUsd:a.availableUsd,withdrawableUsd:a.withdrawableUsd,withdrawableInr:a.withdrawableInr};};
P.sampleEq=function(){const S=this.state.get(),a=this.financial.accountSnapshot(this.state.rate||this.config.BASE_RATE),eq=round((S.inr||0)+a.equityUsd*a.rate),curve=[...(S.equityCurve||[])],now=Date.now(),last=curve[curve.length-1];if(!last||now-last.t>=1000)curve.push({t:now,e:eq});if(curve.length>5000)curve.splice(0,curve.length-5000);this.state.update({equityCurve:curve,peakEquity:Math.max(Number(S.peakEquity)||0,eq)});};
P.checkLiquidations=function(){const S=this.state.get();for(const sym of Object.keys({...S.positions})){const p=this.state.get().positions[sym],m=this.market.getMarket(sym);if(!p||!m||!(m.price>0))continue;const liq=this.financial.liquidationPrice(p);if((p.dir===1&&m.price<=liq)||(p.dir===-1&&m.price>=liq)){const t=this.financial.liquidate(sym,liq);if(t)this.toast('LIQUIDATED',(this.config.SYM_META[sym]||{short:sym}).short+' — '+this.fmtUsd(Math.abs(t.pnl))+' USD lost','err');}}this.flushSave(true);};
P.startSimulationLoop=function(){if(this._financialTimer)clearInterval(this._financialTimer);this._financialTimer=setInterval(()=>{this.checkTPSL();this.checkLiquidations();this.sampleEq();if(this.heatmap)this.heatmap.refresh();this.markDirty();},1000);};
if(global.RiskMetrics){RiskMetrics.prototype.calculate=function(){const s=this.state.getState(),trades=Array.isArray(s.tradeArchive)?s.tradeArchive:[],curve=Array.isArray(s.equityCurve)?s.equityCurve:[],wins=trades.filter(t=>t.pnl>0),losses=trades.filter(t=>t.pnl<0),total=wins.length+losses.length,gp=trades.reduce((a,t)=>a+Math.max(0,Number(t.grossPnl??t.pnl??0)),0),gl=trades.reduce((a,t)=>a+Math.max(0,-Number(t.grossPnl??t.pnl??0)),0),avgWin=wins.length?wins.reduce((a,t)=>a+t.pnl,0)/wins.length:0,avgLoss=losses.length?losses.reduce((a,t)=>a+t.pnl,0)/losses.length:0,wr=total?wins.length/total:0,rs=this.calculateReturns(curve),n=this._periodsPerYear(curve),dd=this.calculateMaxDrawdown(curve),years=this._years(curve),annual=years>0&&curve[0].e>0?Math.pow(curve[curve.length-1].e/curve[0].e,1/years)-1:0;return{maxDrawdown:dd.amount,maxDrawdownPercent:dd.percent,sharpeRatio:this._ratio(rs,n,0.06),sortinoRatio:this._sortino(rs,n),calmarRatio:dd.percent?annual/(dd.percent/100):(annual>0?Infinity:0),winRate:wr*100,profitFactor:gl?gp/gl:(gp?Infinity:0),expectancy:wr*avgWin+(1-wr)*avgLoss,totalTrades:total,winningTrades:wins.length,losingTrades:losses.length,averageWin:avgWin,averageLoss:avgLoss,bestTrade:trades.length?Math.max(...trades.map(t=>t.pnl)):0,worstTrade:trades.length?Math.min(...trades.map(t=>t.pnl)):0,totalFees:s.feesTotal||0,netPnl:trades.reduce((a,t)=>a+Number(t.pnl||0),0),grossProfit:gp,grossLoss:gl};};
RiskMetrics.prototype.calculateReturns=function(c){const r=[];for(let i=1;i<c.length;i++)if(c[i-1].e>0&&c[i].t>c[i-1].t)r.push(c[i].e/c[i-1].e-1);return r;};
RiskMetrics.prototype._periodsPerYear=function(c){if(c.length<2)return 365;const dt=(c[c.length-1].t-c[0].t)/Math.max(1,c.length-1);return dt>0?(365.25*86400000)/dt:365;};
RiskMetrics.prototype._years=function(c){return c.length>1?Math.max(0,(c[c.length-1].t-c[0].t)/(365.25*86400000)):0;};
RiskMetrics.prototype._ratio=function(rs,n,rf){if(rs.length<2)return 0;const prf=Math.pow(1+rf,1/n)-1,e=rs.map(x=>x-prf),m=e.reduce((a,b)=>a+b,0)/e.length,sd=Math.sqrt(e.reduce((a,x)=>a+x*x,0)/(e.length-1));return sd?m/sd*Math.sqrt(n):0;};
RiskMetrics.prototype._sortino=function(rs,n){if(rs.length<2)return 0;const m=rs.reduce((a,b)=>a+b,0)/rs.length,d=Math.sqrt(rs.map(x=>Math.min(0,x)**2).reduce((a,b)=>a+b,0)/rs.length);return d?m/d*Math.sqrt(n):(m>0?Infinity:0);};
}
})(window);
