/* Funding accounting: positive funding credits available USD; negative funding consumes position margin, then liquidates if margin is exhausted. */
(function(global){'use strict';if(!global.FundingSimulator)return;const H=8*60*60*1000,anchor=t=>Math.floor(t/H)*H,round=n=>Math.round(n*1e8)/1e8;
FundingSimulator.prototype.init=function(){const s=this.state.getState();this.lastFundingTime=Number.isFinite(s.lastFundingTime)?s.lastFundingTime:anchor(Date.now());this.checkInterval=setInterval(()=>this.checkFunding(),60000);this.checkFunding();};
FundingSimulator.prototype.checkFunding=function(){const now=Date.now(),next=anchor(now);if(next<=this.lastFundingTime)return;for(let t=this.lastFundingTime+H;t<=next;t+=H)this.applyFunding(t);this.lastFundingTime=next;this.state.update({lastFundingTime:next});};
FundingSimulator.prototype.applyFunding=function(ts=Date.now()){
for(const [symbol,pos0] of Object.entries({...this.state.getState().positions})){const m=this.market.getMarket(symbol);if(!m||!(m.price>0))continue;const rate=Number(m.funding||0);if(!Number.isFinite(rate)||rate===0)continue;const value=pos0.qty*m.price,charge=-pos0.dir*value*rate,S=this.state.getState();let positions={...(S.positions||{})},p={...positions[symbol]},usd=Number(S.usd||0),fundingNet=Number(S.fundingNet||0);
if(charge>=0)usd+=charge;else{const debit=Math.abs(charge),marginUsed=Math.min(Number(p.margin)||0,debit),cashDebit=debit-marginUsed;p.margin=round(Math.max(0,(p.margin||0)-marginUsed));usd=round(Math.max(0,usd-cashDebit));positions[symbol]=p;}
fundingNet=round(fundingNet+charge);this.state.update({usd:round(usd),fundingNet,positions});this.pushLedgerEntry({type:'Funding',detail:symbol,dInr:0,dUsd:round(charge),fundingRate:rate,positionValue:round(value),t:ts});this.events.emit(EVENTS.FUNDING_ACCRUED,{symbol,funding:round(charge),fundingRate:rate,positionValue:round(value),direction:pos0.dir,timestamp:ts});
if(charge<0 && p.margin<=1e-10 && global.financialEngine)global.financialEngine.liquidate(symbol,m.price,'FUNDING_MARGIN_EXHAUSTED');}
this.state.flushSave();};
FundingSimulator.prototype.getNextFundingTime=function(){return new Date(anchor(Date.now()+H));};FundingSimulator.prototype.getTimeUntilFunding=function(){return Math.max(0,this.getNextFundingTime().getTime()-Date.now());};})(window);
