/* Thin paper-account UI adapter. FinancialEngine owns all mutations and snapshots. */
(function(global){
'use strict';
if(!global.DeltaPaperApp)return;
const P=DeltaPaperApp.prototype;
P.applyFill=function(sym,side,price,qty,lev,fee,lots){try{this.financial=this.financial||global.financialEngine;this.financial.fill(sym,side,price,qty,lev,fee,lots,'MARKET');this.flushSave(true);this.markDirty();return true;}catch(e){this.toast('Order rejected',e.message,'err');return false;}};
P.closePosition=function(sym){const pos=this.state.get().positions?.[sym];if(!pos)return false;const m=this.market.getMarket(sym);if(!m||!(m.price>0)){this.toast('No live price','Waiting for market price…','err');return false;}const slip=Number(this.config.CLOSE_SLIPPAGE??0.0003),fill=pos.dir===1?m.price*(1-slip):m.price*(1+slip),fee=Math.abs(fill*pos.qty)*(this.config.TAKER_FEE||0);if(!this.applyFill(sym,-pos.dir,fill,pos.qty,pos.lev,fee,pos.lots))return false;this.toast('Closed',(this.config.SYM_META[sym]||{short:sym}).short+' @ '+this.fmtPrice(fill,m.dec),'ok');return true;};
P.closeAtTrigger=function(pos,label,price){if(!pos||!this.state.get().positions?.[pos.sym])return;const fee=Math.abs(pos.qty*price)*(this.config.TAKER_FEE||0);if(!this.applyFill(pos.sym,-pos.dir,price,pos.qty,pos.lev,fee,pos.lots))return;const trade=this.state.get().tradeArchive?.slice(-1)[0];if(trade){const h=[...(this.state.get().history||[])],i=h.findIndex(x=>x.id===trade.id);if(i>=0)h[i]={...h[i],label};this.state.update({history:h});}this.flushSave(true);const m=this.market.getMarket(pos.sym)||{};this.toast(label,(this.config.SYM_META[pos.sym]||{short:pos.sym}).short+' closed @ '+this.fmtPrice(price,m.dec||2),label==='TP hit'?'ok':'err');};
P.checkLiquidations=function(){const S=this.state.get();for(const sym of Object.keys({...S.positions})){const p=this.state.get().positions[sym],m=this.market.getMarket(sym);if(!p||!m||!(m.price>0))continue;const liq=this.financial.liquidationPrice(p);if((p.dir===1&&m.price<=liq)||(p.dir===-1&&m.price>=liq)){const t=this.financial.liquidate(sym,liq);if(t)this.toast('LIQUIDATED',(this.config.SYM_META[sym]||{short:sym}).short+' — '+this.fmtUsd(Math.abs(t.pnl))+' USD lost','err');}}this.flushSave(true);};
P.totals=function(){const a=this.financial.accountSnapshot(this.state.rate||this.config.BASE_RATE);return{equity:a.unrealizedPnlUsd,lockedMargin:a.lockedMarginUsd,totalEquityUsd:a.equityUsd,accountEquityUsd:a.equityUsd,availableUsd:a.availableUsd,withdrawableUsd:a.withdrawableUsd,withdrawableInr:a.withdrawableInr};};
const oldReset=P.resetAccount;
P.resetAccount=function(){if(!confirm('Reset paper account? Everything will be wiped.'))return;this.state.reset();this.hisLen=-1;this.flushSave(true);this.renderAcct();this.markDirty();this.toast('Reset ✓','Paper account restored to starting balance','ok');};
})(window);
